"""Initial migration

Revision ID: 522b279bd4ca
Revises: 0889b25fcdcc
Create Date: 2019-12-03 21:04:37.558207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522b279bd4ca'
down_revision = '0889b25fcdcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verify_password')
    # ### end Alembic commands ###
