"""Second migration

Revision ID: bcfc2ecc3fa5
Revises: e7bc47cf6ef5
Create Date: 2019-12-04 11:08:06.848675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfc2ecc3fa5'
down_revision = 'e7bc47cf6ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog', sa.Text(), nullable=True))
    op.add_column('blogs', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'user_id')
    op.drop_column('blogs', 'title')
    op.drop_column('blogs', 'blog')
    # ### end Alembic commands ###
