"""Initial migration

Revision ID: dc4fc60591fc
Revises: 522b279bd4ca
Create Date: 2019-12-03 21:23:45.621610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4fc60591fc'
down_revision = '522b279bd4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_pass', sa.String(length=255), nullable=True))
    op.drop_column('users', 'verify_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'verify_pass')
    # ### end Alembic commands ###
