"""Initial migration

Revision ID: e7bc47cf6ef5
Revises: b99e1c9365a1
Create Date: 2019-12-04 10:43:11.974926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7bc47cf6ef5'
down_revision = 'b99e1c9365a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_blog_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('blogs_blog_fkey', 'blogs', 'blogs', ['blog'], ['id'])
    # ### end Alembic commands ###
