"""Initial migration

Revision ID: f30427480f5e
Revises: dc4fc60591fc
Create Date: 2019-12-03 21:31:30.884033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30427480f5e'
down_revision = 'dc4fc60591fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_password', sa.String(length=255), nullable=True))
    op.drop_column('users', 'verify_pass')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_pass', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'verify_password')
    # ### end Alembic commands ###
